#Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
#favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

#Content configuration version
version: 2

# Personal info
name: Dzianis Starasotnikau
title: Lebenslauf
email: destarvision@gmail.com
# email_title: Email (Email title override)
phone: 01786566221
# phone_title: Phone (Phone title override)
#website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true 

# Social links
#twitter_username: jekyllrb
github_username:  denis23000
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: dzianis-starasotnikau-085888230
xing_username: Dzianis_Starasotnikau
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

#About Section
about_title: About
about_profile_image: images/profile.jpg
about_content: Herzlich wilkomen zu meinem Online-Lebenslauf. Ich heiße Dzianis und urschprünglich komme ich aus Belarus. 
  Zurzeit wohne ich in München und ich habe mich für einen neuen Beruf entschieden, und zwar für Programmierung. 
  Darum mache ich seit 2022 bei DIDACT München eine Umschulung zum Fachinformatiker für Anwendungsentwicklung. 
  Von neuem Beruf bin ich total begeistert! Mit großem Interesse lerne ich viele interessante Fächer, die für mich neu sind, und bekomme gute Noten. 
  Darüber hinaus bin ich zwischen durch ein Kursteilnehmer bei der REDI School München, wo ich den Kurs “Introduction to Computer Science” abgeschlossen habe, und nun bin ich dort am Kurs “Python Intermediate”.
  <br/>
  In meiner Freizeit finden Sie mich am Fußballplatz, da ich ein aktives Mitglid beim Fußballverein bin.
  <br/><br/>
  <font size="5">Fähigkeiten und Kenntnisse:</font>
  
  <mark>HTML</mark>
  <mark>CSS</mark>
  <mark>Python</mark>
  <mark>C++</mark>
  <mark>SQL</mark>
  <mark>Linux</mark>
  <mark>Git</mark>
  <mark>GitHub</mark>
  <mark>MS Office</mark>

  <font size="5">Sprachen:</font>
  
  <mark>Russisch</mark>    Muttersprache <br/>
  <mark>Deutsch</mark>     Fließend  <br/>
  <mark>Englisch</mark>    Grundkenntnisse <br/>
  <mark>Italienisch</mark> Grundkenntnisse <br/>



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: website www.musicbydenis.de
        link: http://www.musicbydenis.de/
        link_text: Link to Projekt
        additional_links:
          - title:  Link to project
            icon: fab fa-github
            url: https://github.com/denis23000/musicbydenis 
        quote: >
           
        description: | # this will include new lines to allow paragraphs
          Eine einfache Internetseite, die ich entwickelt und bereitgestellt habe (HTML, checkdomain, IONOS)
      - layout: left
        title: Online Lebenslauf
        link: https://denis23000.github.io/Lebenslauf/
        link_text: Link to Projekt
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/denis23000/Lebenslauf
        quote: 
        description: | # this will include new lines to allow paragraphs
          Erstellung vom Online-Lebenslauf mittels Muster von James Grant (HTML, CSS, Ruby, Bundle, jekyll)
      - layout: left
        title: ATM_REDI_ICS
        link: https://github.com/denis23000/ATM_REDI_ICS
        link_text: Link to Projekt
        additional_links:    
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/denis23000/ATM_REDI_ICS
        quote:   
        description: | # this will include new lines to allow paragraphs
          Abschlussprojekt bei dem Kurs "Introduction to Computer sience" bei der REDI Scool. Für den Abschlussprojekt habe ich ein Geldautomat programmiert (Python)
  #- title: Experience
    #layout: list
    #content:
      #- layout: left
        #title: Company name
        #sub_title: Job title
        #caption: Date Range (eg. November 2016 - present)
        #link: 
        #quote: >
         
        #description: | # this will include new lines to allow paragraphs
        
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: DIDACT Kaufm. Berufsbildungsges mbH, München
        sub_title:  Umschulung zum Fachinformatiker für Anwendungsentwicklung. IHK Abschluss.
        caption: 01.2022 - 11.2023
        quote:  
        description: | # this will include new lines to allow paragraphs
         IT-Grundlagen, PC-MS-Office-Anwenderprogramme, Datenbankentwiklung/<mark>SQL</mark>, <mark>HTML</mark>, <mark>Python</mark>, <mark>C++</mark>, <mark>CSS</mark>, <mark>Linux</mark>, Srukturierte Programmierung, Netzwerktechnik, Wirtschafts- und Sozialkunde, Projektmanagemet, Englisch for Computing, Deutsch/Kfm. Schriftverkehr, Berufsbezogenes Rechnen.
      - layout: top-left
        title: REDI Scool
        sub_title: Introduction to Computer Sience
        caption: 03.2022 - 06.2022
        quote: 
        description: | # this will include new lines to allow paragraphs
          Basic Command Line <mark>Linux</mark>. Understand basics of an operating system. Create hard and soft links. Navigate the Linux file system. Version Control with <mark>GIT</mark>. Web Fundamentals. Understand web concepts and basic knowledge of <mark>HTML</mark>, <mark>CSS</mark> and <mark>JavaScript</mark> Introduction to Programming <mark>Python</mark>. Understand basic python programming. Understand Data types, Operations, Conditionals, Functions. Understand Python classes and objects
  #- title: A Little More About Me
    #layout: text
    #content: | # this will include new lines to allow paragraphs
    #  In meiner Freizeit finden Sie mich am Fußballplatz, da ich ein aktives Mitglid beim Fußballverein bin.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
